
import pandas as pd
import matplotlib.pyplot as plt

# Read CSV file generated by C program
data = pd.read_csv("../data/schedule_log.csv")

fig, ax = plt.subplots()

colors = {}

for i in range(len(data)):
    pid = data.loc[i, "pid"]
    start = data.loc[i, "start"]
    end = data.loc[i, "end"]

    duration = end - start

    # Assign a color to each process
    if pid not in colors:
        colors[pid] = plt.cm.tab10(pid % 10)

    ax.barh(
        y=f"P{pid}",
        width=duration,
        left=start,
        color=colors[pid],
        edgecolor="black"
    )

    # Label inside bar
    ax.text(start + duration/2, f"P{pid}", f"P{pid}",
            ha="center", va="center", color="white")

ax.set_xlabel("Time")
ax.set_ylabel("Processes")
ax.set_title("CPU Scheduling Gantt Chart")

plt.tight_layout()
plt.show()
