import pandas as pd
import matplotlib.pyplot as plt

# Read CSV file generated by C program
data = pd.read_csv("data/schedule_log.csv")

plt.style.use("dark_background")

fig, ax = plt.subplots(figsize=(10,4))

colors = {}

for i in range(len(data)):
    pid = data.loc[i, "pid"]
    start = data.loc[i, "start"]
    end = data.loc[i, "end"]

    duration = end - start

    # Assign consistent colors
    if pid not in colors:
        colors[pid] = plt.cm.tab10(pid % 10)

    ax.barh(
        y=0,
        width=duration,
        left=start,
        height=0.6,
        color=colors[pid],
        edgecolor="none"
    )

    # Label inside bar
    ax.text(
        start + duration/2,
        0,
        f"P{pid}",
        ha="center",
        va="center",
        color="white",
        fontsize=14,
        fontweight="bold"
    )

# Remove y-axis
ax.set_yticks([])

# Time ticks
times = sorted(set(data["start"]).union(set(data["end"])))
ax.set_xticks(times)

# Title
ax.set_title("Gantt Chart", fontsize=26, loc="left", pad=20)

# Remove borders
for spine in ax.spines.values():
    spine.set_visible(False)

ax.tick_params(axis='x', labelsize=12)

plt.tight_layout()
plt.show()

